# Parte A

### Ejercicio 1.0

Importar los módulos necesarios

In [3]:
import math
import numpy as np

### Ejercicio 1.1

Calculemos el producto matricial, la matriz transpuesta y el determinante

In [3]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7,8]])

producto_matricial = np.matmul(matriz1, matriz2)
transpuesta = np.transpose(matriz1)
determinante = np.linalg.det(matriz1)

print("Producto matricial: ")
print(producto_matricial)
print("Transpuesta de la matriz:")
print(transpuesta)
print("Determinante de la matriz: ")
print(determinante)

Producto matricial: 
[[19 22]
 [43 50]]
Transpuesta de la matriz:
[[1 3]
 [2 4]]
Determinante de la matriz: 
-2.0000000000000004


### Ejercicio 1.2

NumPy tiene una función específica para resolver ecuaciones lineales

In [4]:
coeficientes = np.array([[2, 3], [4, -1]])
constantes = np.array([5, 2])

solucion = np.linalg.solve(coeficientes, constantes)
print("Solución del sistema de ecuaciones: ")
print("x =", solucion[0])
print("y=", solucion[1])

Solución del sistema de ecuaciones: 
x = 0.7857142857142857
y= 1.1428571428571428


### Ejercicio 1.3

Exploremos funciones para conocer las dimensiones de un array multidimensional

In [6]:
array_multidimensional = np.array([[[0, 1, 2, 3] , [4, 5, 6, 7]],
                                    [[0, 1, 2, 3],[4, 5, 6, 7]],
                                        [[0, 1, 2, 3],[4, 5, 6, 7]]])


In [7]:
array_multidimensional.ndim

3

In [8]:
array_multidimensional.size

24

In [9]:
array_multidimensional.shape

(3, 2, 4)

### Ejercicio 1.4

Veamos que posibilidades hay para indexar valores y separar un array.

In [10]:
array_indexado = np.array([1, 2, 3, 4, 5, 6, 7])

In [11]:
array_indexado[0]

1

In [12]:
array_indexado[1]

2

In [13]:
array_indexado[0:2]

array([1, 2])

In [14]:
array_indexado[4:]

array([5, 6, 7])

In [15]:
array_indexado[-1:]

array([7])

### Ejercicio 1.5

Veamos cómo utilizar la función sort.

In [16]:
array_desordenado = np.array([3, 1, 5, 2, 4])

array_ordenado = np.sort(array_desordenado)

array_ordenado 


array([1, 2, 3, 4, 5])

### Ejercicio 1.6

Además de ordenar un array podemos invertir el orden de los valores.

In [17]:
array_original = np.array([1, 2, 3, 4, 11, 12, 13, 14, 15, 5, 6, 7, 8])

array_reverso = np.flip(array_original)
array_reverso 

array([ 8,  7,  6,  5, 15, 14, 13, 12, 11,  4,  3,  2,  1])

### Ejercicio 1.7

Crear un array con números aleatorios.

In [18]:
rng = np.random.default_rng()

In [19]:
rng.random(3)

array([0.11430445, 0.09665996, 0.956853  ])

In [20]:
rng.integers(5, size=(2,4))

array([[1, 1, 4, 0],
       [4, 4, 0, 0]])

### Ejercicio 1.8

Contar valores únicos dentro de un array.

In [22]:
array_repetidos = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20, 11, 12, 13, 14, 15, 16, 17, 11, 14, 18, 19, 20])

array_unicos = np.unique(array_repetidos)
array_unicos 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Parte B

Tenemos una función cúbica con la forma (3x^3-7x^2+6*x+9)

In [23]:
def mi_funcion(x):
    return 3 * x**3 - 7 * x**2 + 6 * x + 9

### Ejercicio 2.1

Calcular cuáles serían los valores obtenidos al pasarle como argumentos los valors pares desde 0 a 20, incluyendo ambos. Guarden el resultado en un array.

In [24]:
lista_valores_x = []
for i in range(0, 21, 2):
    lista_valores_x.append(i)
input_array = np.array(lista_valores_x)
input_array 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
output_array = mi_funcion(input_array)
output_array

array([    9,    17,   113,   441,  1145,  2369,  4257,  6953, 10601,
       15345, 21329])

### Ejercicio 2.2

Con el array que obtuvimos en la sección anterior vamos a trabajar:
- Calcular la media de los números en el array que contiene los valores calculados.
- Calcular la desviación estándar de los números en el array calculado.
- Crear un nuevo array array_cuadrados que contenga el cuadrado de cada números calculado.
- Crear un array con la suma acumulativa (a1, a1 + a2, a1 + a2 + a3,...) de los elementos en array_cuadrados.
- Crear un array con la raíz 5ta de cada valor de array_cuadrados(redondear a 2 decimales)

Imprimir los resultados obtenidos.

In [26]:
media = np.mean(output_array)

desviacion_estandar = np.std(output_array)

valor_maximo = np.max(output_array)

indice_maximo = np.argmax(output_array)

array_cuadrados = np.square(output_array)

suma_acumulativa_cuadrados = np.cumsum(array_cuadrados)

array_raiz_quinta = np.power(array_cuadrados, 1/5).round(2)

print("Media: ", media)
print("Desviación Estándar: ", desviacion_estandar)
print("Valor Máximo: ", valor_maximo)
print("Índice del Valor Máximo: ", indice_maximo)
print("Valores al Cuadrado: ", array_cuadrados)
print("Array Suma Acumulativa de Valores al Cuadrado: ", suma_acumulativa_cuadrados)
print("Array Resultado Raíz Quinta: ", array_raiz_quinta)

Media:  5689.0
Desviación Estándar:  6877.906658279102
Valor Máximo:  21329
Índice del Valor Máximo:  10
Valores al Cuadrado:  [       81       289     12769    194481   1311025   5612161  18122049
  48344209 112381201 235469025 454926241]
Array Suma Acumulativa de Valores al Cuadrado:  [       81       370     13139    207620   1518645   7130806  25252855
  73597064 185978265 421447290 876373531]
Array Resultado Raíz Quinta:  [ 2.41  3.11  6.63 11.42 16.73 22.38 28.29 34.42 40.75 47.25 53.9 ]


### Ejercicio 2.3

Con los arrays que obtuvimos en la sección anterior vamos a hacer:
- Calcular el producto escalar (o producto punto) entre los array_output y el array_raiz_quinta.
- Crear un vector con los últimos 3 valores del array_input. Crear un segundo vector con los 3 primeros valores del array suma_acumulativa_cuadrados. Calcular el array que daría como resultado hacer el producto vectorial entre ambos.

In [27]:
resultado_producto_escalar = np.matmul(output_array, array_raiz_quinta).round(2)
resultado_producto_escalar

2744461.93

In [29]:
vector1 = input_array[-3:]
vector2 = suma_acumulativa_cuadrados[:3]
resultado_producto_escalar = np.cross(vector1, vector2)
resultado_producto_escalar

array([ 229102, -208604,    4462])