# Introducción al trabajo con módulos

Los módulos en Python son como cajas de herramientas que contienen conjuntos de funciones y variables que pueden ser utilizadas para realizar tareas específicas.

Estos compartimentos organizados guardan diferentes herramientas para hacer diferentes trabajos.

Se puede usar estos módulos simplemente llamándolos en tu programa cuando los necesites, y así aprovechar todas las funcionalidades que ofrecen sin tener que volver a escribir todo el código desde cero. 

Para importar cualquier módulo es muy simple:

import < nombre_modulo >

Podemos asignarle un alias al importarlo:

import < nombre_modulo > as < alias >

O si vamos a utilizar solo una parte de todo el módulo y no queremos sobrecargar la memoria con cosas innecesarias podemos importar un paquete en particular:

from < nombre_modulo > import < nombre_paquete > as < alias > (opcional)

## Instalar módulos

A la hora de trabajar con módulos es posible que no los tengamos instaladas ya que muchos son creados por la comunidad o simplemente no están incluidos con los archivos base de Python.

Para ello podemos usar pip:
- En la terminal(local): pip install < nombre_modulo >
- En colab ejecutar en una celda: !pip install < nombre_modulo >

## Math

El módulo math en Python se utiliza para realizar operaciones matemáticas más avanzadas que las disponibles en el conjunto de funciones y permite utilizar constantes matemáticas básicas para manejar problemas más complejos que requieren operaciones matemáticas avanzadas.

Incluy funciones para:
- Realizar cálculos trigonométricos
- Operaciones de álgebra linear
- Funciones exponenciales y logarítmicas

### Ejercicio 1.0

Importar el módulo math

In [1]:
import math

### Ejercicio 1.1

Calculadora de Área de un Círculo

In [2]:
radio = float(input("Ingrese el radio del círculo: "))
area = math.pi * radio ** 2
print("El área del círculo es: ", area)

Ingrese el radio del círculo:  5


El área del círculo es:  78.53981633974483


### Ejercicio 1.2 

Calculadora de Hipotenusa 

In [3]:
cateto1 = float(input("Ingrese la longitud del primer cateto: "))
cateto2 = float(input("Ingrese la longitud del segundo cateto: "))
hipotenusa = math.sqrt(cateto1 ** 2 + cateto2 ** 2)
print("La longitud de la hipotenusa es: ", hipotenusa)

Ingrese la longitud del primer cateto:  3
Ingrese la longitud del segundo cateto:  4


La longitud de la hipotenusa es:  5.0


### Ejercicio 1.3

Calculadora seno, coseno y tangente

In [4]:
angulo_grados = float(input("Ingrese el ángulo en grados: "))
angulo_radianes = math.radians(angulo_grados)

seno = math.sin(angulo_radianes)
coseno = math.cos(angulo_radianes)
tangente = math. tan(angulo_radianes)

print("Seno: ", seno)
print("Coseno: ", coseno)
print("Tangente: ", tangente)

Ingrese el ángulo en grados:  20


Seno:  0.3420201433256687
Coseno:  0.9396926207859084
Tangente:  0.36397023426620234


### Ejercicio 1.4

Cálculo de potencias

In [5]:
base = float(input("Ingrese la base: "))
exponente =float(input("Ingrese el exponente: "))
resultado = math.pow(base, exponente)
print("El resultado de ", base, " elevado a la ", exponente, " es ", resultado)

Ingrese la base:  3
Ingrese el exponente:  -6


El resultado de  3.0  elevado a la  -6.0  es  0.0013717421124828531


### Ejercicio 1.5 

Área de un triángulo (fórmula de Herón)

In [7]:
lado1 = 5
lado2 = 6
lado3 = 7

s = (lado1 + lado2 + lado3) / 2

area = math.sqrt(s*(s - lado1) * (s - lado2) * (s - lado3))
print("El área del triángulo es: ", area)

El área del triángulo es:  14.696938456699069


### Ejercicio 1.6

Suma de una serie infinita (π/4 = 1 - 1/3 + 1/5 - 1/7 + 1/9 - ...) 

In [8]:
suma = 0 
terminos = 1000

for i in range(terminos):
    suma += (-1) ** i / (2 * i + 1)

pi = 4 * suma
print("El valor de π aproximado es: ", pi)

El valor de π aproximado es:  3.140592653839794


## NumPy

NumPy es una biblioteca de Python que ayuda a trabajar con matrices y arreglos multidimensionales.

Con Numpy se puede realizar:
- Multiplicación de matrices/arreglos
- Inversión de matrices/arreglos
- Cálculo de funciones trigonométricas
- Procesamiento de datos
- Manipulación de matrices grandes de manera rápida y eficiente.

En resumen NumPy se usa para trabajar con datos numéricos en Python.

### Ejercicio 2.0

Importar NumPy pero usando el alias np

In [9]:
import numpy as np

### Ejercicio 2.1

Veremos las operaciones básicas con arrays

In [11]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

suma = array1 + array2
resta = array1 - array2
multiplicacion = array1 * array2
division = array1 / array2

print("Suma: ", suma)
print("Resta: ", resta)
print("Multiplicación: ", multiplicacion)
print("División: ", division)

Suma:  [ 7  9 11 13 15]
Resta:  [-5 -5 -5 -5 -5]
Multiplicación:  [ 6 14 24 36 50]
División:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


### Ejercicio 2.2

Con NumPy es muy fácil crear matrices, por ejemplo la matriz de Identidad

In [12]:
matriz_identidad = np.eye(5)
print("Matriz de identidad 5x5: ")
print(matriz_identidad)

Matriz de identidad 5x5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Ejercicio 2.3

Si trabajamos con vectores podemos calcular el producto escalar de estos

In [13]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

producto_escalar = np.dot(vector1, vector2)
print("Producto escalar: ", producto_escalar)

Producto escalar:  32


### Ejercicio 2.4

Otra operación muy común es calcular el vector norma.

In [14]:
vector = np.array([3, 4])
norma = np.linalg.norm(vector)
print("Norma del vector: ", norma)

Norma del vector:  5.0


### Ejercicio 2.5

De forma similar es posible realizar operaciones entre matrices usando NumPy.

In [15]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

producto_matricial = np.matmul(matriz1, matriz2)
transpuesta = np.transpose(matriz1)
determinante = np.linalg.det(matriz1)

print("Producto matricial: ")
print(producto_matricial)
print("Transpuesta de la matriz: ")
print(transpuesta)
print("Determinante de la matriz: ")
print(determinante)

Producto matricial: 
[[19 22]
 [43 50]]
Transpuesta de la matriz: 
[[1 3]
 [2 4]]
Determinante de la matriz: 
-2.0000000000000004


### Ejercicio 2.6

NumPy tiene una función específica para resolver ecuaciones lineales.

In [16]:
coeficientes = np.array([[2, 3], [4, -1]])
constantes = np.array([5, 2])

solucion = np.linalg.solve(coeficientes, constantes)
print("Solución del sistema de ecuaciones: ")
print("x = ", solucion[0])
print("y = ", solucion[1])

Solución del sistema de ecuaciones: 
x =  0.7857142857142857
y =  1.1428571428571428
